/// <reference types="cypress" />

// ***********************************************************
// This example support/e2e.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// Import commands.js using ES2015 syntax:
import './commands';
import 'cypress-plugin-steps';
import '@testing-library/cypress/add-commands';
import { geolocations } from './testData';

import {
    logStep,
    clearAllSessionData,
    iFrame,
    generateRandomTestEmail,
} from '../../../_libs/commands';

import {
    checkCartOrders,
    checkAccountOrders,
    createNewGtin,
    deleteGtinsTestData,
    deleteProductsTestDataNoTrashed,
    loginToAdminTool,
    searchAndAddOffer,
    processPayment,
    loginToQuietLogistics,
    loginToDeposco,
    loginToSculptNationAccount,
    createUserInAdminTool,
    deleteUserInAdminTool,
    navigateToNewOrderPage,
    addShippingAndBillingAddressVsAdmin,
    addNewShippingAddress,
    cancelSubscriptionFromAdminTool,
    skipVideo,
    checkEmail,
    checkEmailContent,
    checkOrderEmailContents,
    getEmailData,
    getEmailDataVshred,
    getEmailContent,
    validateOfferPages,
    createNewLeOffer,
    deleteOffersTestData,
    fillInSurveyOrderForm,
    fillInShippingOrderForm,
    fillInSupplementOrderForm,
    fillInLeOrderForm,
    fillInLeOrderFormInvalidCreditCard,
    validateProductsPages,
    createNewLeProduct,
    editLeProducts,
    restoreProductsTestData,
    attachResource,
    deleteProductsTestData,
    validateRolesPages,
    addPermissions,
    createNewRole,
    validatePermissionsPages,
    createNewPermission,
    addRoles,
    validateDiscountsPages,
    createNewDiscount,
    getResourceValues,
    editResourceDetails,
    deleteDiscountsTestData,
    filloutCheckoutV3,
    filloutSnCheckoutFb,
    validatePlansPages,
    validateOrdersPages,
    validateOrderDetails,
    validateSubscriptionsPages,
    validateSubscriptionResource,
    navigateToSubscriptionResource,
    validatePaymentsPages,
    validatePaymentResource,
    navigateToPaymentResource,
    validateShipmentsPages,
    validateShippingCategoriesPages,
    validateShippingCarriersPages,
    createNewCarrier,
    validateShippingFulfillmentLogsPages,
    createNewSalesAgent,
    createNewLePlan,
    deletePlansTestData,
    validatePageSection,
    viewOrderDetails,
    updateAccountDetails,
    updateUserPassword,
    addProductByBottleToCart,
    addBundleByBottleToCart,
    createNewAddress,
    createUserViaiFrame,
    executeFileAction,
    executeFolderAction,
    logoutLeAdmin,
    getLeAdminToken,
    loginAsNewAdminUser,
    validateDashboardPage,
    validateCheckoutFormPages,
    createBumperTemplate,
    createBumper,
    createCarousel,
    createReviews,
    deleteCheckoutFormRecords,
    viewFunnelOrderDetails,
    generateRandomSurveyResponse,
    randomVsSurveyResponse,
    loginToVshredAdminTool,
    assignTrainer,
    filloutCustomQuestionnaire,
    completeVsMemberProfile,
    filloutLEcheckoutForm,
    fillInFunnelOrderForm,
    fillInSurveyFormWithUpsell,
    fillInSupplementOrderFormSurvey,
    refundOrderItem,
    filloutVsOrderForm,
    stordGetShipmentStatus,
    stordCreateShipment,
    stordCancelShipment,
    loginToEnvoyer,
    getKlaviyoMetrics,
    checkKlaviyoEvents,
    setEnvoyerEnvVar,
    filloutVsUcpCheckout,
    filloutPayPalForm,
    unAssignTrainer,
    checkOrderForm,
    filloutVsEcomCheckout,
    selectVsProgram,
    addOfferVsAdmin,
    filloutAcceleratorQuestionnaire,
    filloutEliteQuestionnaire,
    filloutVsSurveyCheckout,
    randomNewVsSurveyResponse,
    filloutLegacyVsOrderForm,
    filloutVsShippingForm,
    checkVsOrderForm,
    interceptPixels,
    verifyPixelDetails,
    filloutFastCheckoutForm,
    filloutVsSecureCheckout,
    filloutSNSecureCheckoutForm,
    createSelfRefund,
    checkSelfRefund,
    filloutVsCheckoutFle,
    adyenCheckout,
    randomNewBodyTypeSurvey,
    hormoneQuiz,
    filloutPaymentInformation,
    trackSnapchatEvents,
    filloutSecureCheckoutForm,
    verifySnapchatPixels,
    checkFunnelErrorMessage,
    filloutFastCheckoutFormWithMissingValues,
    filloutFLEFormWithMissingValues,
    surveyGaRefreshPageTests,
} from '../commands';

Cypress.Commands.addAll({
    generateRandomTestEmail,
    logStep,
    clearAllSessionData,
    loginToAdminTool,
    loginToQuietLogistics,
    loginToDeposco,
    loginToSculptNationAccount,
    searchAndAddOffer,
    iFrame,
    processPayment,
    createUserInAdminTool,
    deleteUserInAdminTool,
    navigateToNewOrderPage,
    addShippingAndBillingAddressVsAdmin,
    addNewShippingAddress,
    cancelSubscriptionFromAdminTool,
    skipVideo,
    checkEmail,
    checkEmailContent,
    getEmailData,
    getEmailDataVshred,
    getEmailContent,
    checkOrderEmailContents,
    checkCartOrders,
    checkAccountOrders,
    validateOfferPages,
    createNewLeOffer,
    deleteOffersTestData,
    fillInSurveyOrderForm,
    fillInShippingOrderForm,
    fillInSupplementOrderForm,
    fillInLeOrderForm,
    fillInLeOrderFormInvalidCreditCard,
    validateProductsPages,
    createNewLeProduct,
    editLeProducts,
    restoreProductsTestData,
    attachResource,
    deleteProductsTestData,
    validateRolesPages,
    addPermissions,
    createNewRole,
    validatePermissionsPages,
    createNewPermission,
    addRoles,
    validateDiscountsPages,
    createNewDiscount,
    getResourceValues,
    editResourceDetails,
    deleteDiscountsTestData,
    filloutCheckoutV3,
    filloutSnCheckoutFb,
    validatePlansPages,
    validateOrdersPages,
    validateOrderDetails,
    validateSubscriptionsPages,
    validateSubscriptionResource,
    navigateToSubscriptionResource,
    createNewGtin,
    deleteGtinsTestData,
    deleteProductsTestDataNoTrashed,
    validatePaymentsPages,
    validatePaymentResource,
    navigateToPaymentResource,
    validateShipmentsPages,
    validateShippingCategoriesPages,
    validateShippingCarriersPages,
    createNewCarrier,
    validateShippingFulfillmentLogsPages,
    createNewSalesAgent,
    createNewLePlan,
    deletePlansTestData,
    validatePageSection,
    viewOrderDetails,
    updateAccountDetails,
    updateUserPassword,
    addProductByBottleToCart,
    addBundleByBottleToCart,
    createNewAddress,
    createUserViaiFrame,
    executeFileAction,
    executeFolderAction,
    logoutLeAdmin,
    getLeAdminToken,
    loginAsNewAdminUser,
    validateDashboardPage,
    validateCheckoutFormPages,
    createBumperTemplate,
    createBumper,
    createCarousel,
    createReviews,
    deleteCheckoutFormRecords,
    viewFunnelOrderDetails,
    generateRandomSurveyResponse,
    randomVsSurveyResponse,
    loginToVshredAdminTool,
    assignTrainer,
    filloutCustomQuestionnaire,
    completeVsMemberProfile,
    filloutLEcheckoutForm,
    fillInFunnelOrderForm,
    fillInSurveyFormWithUpsell,
    fillInSupplementOrderFormSurvey,
    refundOrderItem,
    filloutVsOrderForm,
    stordGetShipmentStatus,
    stordCreateShipment,
    stordCancelShipment,
    loginToEnvoyer,
    getKlaviyoMetrics,
    checkKlaviyoEvents,
    setEnvoyerEnvVar,
    filloutVsUcpCheckout,
    filloutPayPalForm,
    unAssignTrainer,
    checkOrderForm,
    filloutVsEcomCheckout,
    selectVsProgram,
    addOfferVsAdmin,
    filloutAcceleratorQuestionnaire,
    filloutEliteQuestionnaire,
    filloutVsSurveyCheckout,
    randomNewVsSurveyResponse,
    filloutLegacyVsOrderForm,
    filloutVsShippingForm,
    checkVsOrderForm,
    interceptPixels,
    verifyPixelDetails,
    filloutFastCheckoutForm,
    filloutVsSecureCheckout,
    filloutSNSecureCheckoutForm,
    createSelfRefund,
    checkSelfRefund,
    filloutVsCheckoutFle,
    adyenCheckout,
    randomNewBodyTypeSurvey,
    hormoneQuiz,
    filloutPaymentInformation,
    trackSnapchatEvents,
    filloutSecureCheckoutForm,
    verifySnapchatPixels,
    checkFunnelErrorMessage,
    filloutFastCheckoutFormWithMissingValues,
    filloutFLEFormWithMissingValues,
    surveyGaRefreshPageTests,
});

Cypress.on(
    'uncaught:exception',
    // eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars
    (err, runnable) =>
        // returning false here prevents Cypress from
        // failing the test
        false
);

beforeEach(() => {
    cy.intercept('*', (req) => {
        req.headers['is-qa-automation'] = 'true';
    });

    /**
     * Use this URL locally to test your geolocation change: https://www.w3schools.com/html/html5_geolocation.asp
     * Just replace the / in the cy.visit command with the URL, and once the page loads, click the Try it! button to see the geolocation
     */
    const testGeolocation = Cypress.env('GEOLOCATION');

    if (testGeolocation) {
        const city = testGeolocation as keyof typeof geolocations;
        const { latitude } = geolocations[city];
        const { longitude } = geolocations[city];

        cy.log(`Tests are running this geolocation: ${testGeolocation}`);

        Cypress.automation('remote:debugger:protocol', {
            command: 'Emulation.setGeolocationOverride',
            params: {
                latitude,
                longitude,
                accuracy: 50,
            },
        });
    }
});
